version: '3.8'

services:

  raccoon-exchange:
    container_name: raccoon-exchange-service-dev
    image: masked-trader/exchange-service:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - ./.env.development
    volumes:
      - ./src/:/workspace/app/
    networks:
      - raccoon-proxy-network-dev
      - raccoon-exchange-network-dev
    depends_on:
      - mongodb
    restart: unless-stopped

  raccoon-proxy:
    container_name: raccoon-proxy-service-dev
    image: nginx
    ports:
      - 80:80
      - 5284:5284
    volumes:
      - ./files/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./files/nginx/snippets:/etc/nginx/snippets:ro
    networks:
      - raccoon-proxy-network-dev
    restart: unless-stopped

  raccoon-configuration:
    container_name: raccoon-configuration-service-dev
    image: masked-trader/configuration-service:dev
    build:
      context: github.com/masked-trader/raccoon-configuration-service.git
      dockerfile: ./Dockerfile
      target: development
    environment:
      RACCOON_REDIS_HOST: redis
      RACCOON_MONGO_CONNECTION_URL: mongodb://root:rootpassword@mongodb:27017
    depends_on:
      - redis
      - mongodb
    networks:
      - raccoon-proxy-network-dev
      - raccoon-config-network-dev
    restart: unless-stopped

  redis:
    container_name: raccoon-redis-dev
    image: redislabs/redistimeseries
    restart: unless-stopped
    command: redis-server --save "" --appendonly no --loadmodule /usr/lib/redis/modules/redistimeseries.so
    networks:
      - raccoon-config-network-dev
    volumes:
      - redis-data-dev:/data/

  mongodb:
    container_name: raccoon-mongodb-dev
    image: mongo:5
    environment:
      MONGO_INITDB_DATABASE: raccoon
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - raccoon-config-network-dev
      - raccoon-exchange-network-dev
      - raccoon-mongo-express-network-dev
    volumes:
      - mongodb-data-dev:/data/db
      - mongodb-data-dev:/data/configdb
    restart: unless-stopped

  mongo-express:
    container_name: raccoon-mongo-express-dev
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - 8081:8081
    networks:
      - raccoon-mongo-express-network-dev
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  redis-data-dev:
  mongodb-data-dev:

networks:
  raccoon-proxy-network-dev:
  raccoon-config-network-dev:
  raccoon-exchange-network-dev:
  raccoon-mongo-express-network-dev:
